### ISSUE TITLE
Update to latest binutils, glibc and GCC

### ISSUE THREAD

**Issue by ghost** [graysky2/crosstool-ng_for_distcc#5]
The prebuilt toolchains are built on 20210515 (from the config, it seems to be based on binutils 2.36, glibc 2.33, and GCC 11.1.0) but there are new versions of binutils (2.38) , glibc (2.35) and GCC (11.2.0).

-----

P.S. Thank you for this repo and the prebuilt toolchains.
I guess using Clang may be more convenient, but I think the target has to be specified explicitly (e.g. for CMake `-DCMAKE_C_COMPILER_TARGET="x86_64-pc-linux-gnu" -DCMAKE_CXX_COMPILER_TARGET="x86_64-pc-linux-gnu"`) so that distcc on the ARM volunteers will compile for x86_64.
(Maybe this is a bug of distcc, icecc/icecream will [add the target for Clang automatically](https://github.com/icecc/icecream/commit/1f883606b354dd5fb8b95c8b889ed37aad4e8fbb))

**Comment by graysky2** [comment]
I haven't been using this since updating my workstation.  Are you able to test/verify that a new version works as intended?

**Comment by jiriks74** [comment]
> I haven't been using this since updating my workstation.  Are you able to test/verify that a new version works as intended?

I'm using rpios rn, but I'm try to find an sdcard and test the builds

**Comment by graysky2** [comment]
The [AUR package](https://aur.archlinux.org/packages/distccd-x86_64) has been updated.  Please test and confirm it works properly.

**Comment by ghost** [comment]
Thank you very much for the update!
